# Generated by Django 5.2.8 on 2025-11-18 06:25

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_number_verified",
            field=models.BooleanField(
                default=False,
                help_text="Choose whether phone number has been verified via SMS",
            ),
        ),
        migrations.CreateModel(
            name="PhoneVerication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("verification_code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Phone Verification",
                "verbose_name_plural": "Phone Verifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone_number", "verified_at"],
                        name="accounts_ph_phone_n_8605c2_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="accounts_ph_user_id_35371b_idx",
                    ),
                ],
            },
        ),
    ]
