# Generated by Django 4.2.25 on 2025-10-21 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_userprofile_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="This will be your name others will know you as.",
                max_length=225,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
