# Generated by Django 5.2.8 on 2025-11-18 07:12

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_customuser_phone_number_verified_phoneverication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Thie name others will know you as.",
                max_length=225,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number_verified",
            field=models.BooleanField(
                default=False,
                help_text="Has this phone number has been verified via SMS?",
            ),
        ),
        migrations.CreateModel(
            name="PhoneVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("verification_code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Code expires in 10 minutes after creation"
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Failed verification attempts for this code (Max 5)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Phone Verification",
                "verbose_name_plural": "Phone Verifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="PhoneVerication",
        ),
        migrations.AddIndex(
            model_name="phoneverification",
            index=models.Index(
                fields=["phone_number", "verified_at"],
                name="accounts_ph_phone_n_ea0b11_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="phoneverification",
            index=models.Index(
                fields=["user", "created_at"], name="accounts_ph_user_id_efa1c8_idx"
            ),
        ),
    ]
