# Generated by Django 4.2.25 on 2025-10-21 18:14

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_customuser_display_name_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[accounts.models.validate_not_future_date],
            ),
        ),
    ]
