# Generated by Django 4.2.25 on 2025-10-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_userprofile_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user's email has been verified",
                verbose_name="Email verified",
            ),
        ),
    ]
