"""
Django settings for mini_ecom project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from datetime import timedelta
import os
from pathlib import Path
import warnings
from dotenv import load_dotenv
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# dj-rest-auth currently triggers deprecation warnings when importing its registration
# serializers against newer allauth versions. Filter these specific warnings to
# keep production logs clean until dependencies are upgraded.
warnings.filterwarnings(
    "ignore",
    message=r"app_settings\.USERNAME_REQUIRED is deprecated.*",
    category=UserWarning,
    module=r"dj_rest_auth\.registration\.serializers",
)
warnings.filterwarnings(
    "ignore",
    message=r"app_settings\.EMAIL_REQUIRED is deprecated.*",
    category=UserWarning,
    module=r"dj_rest_auth\.registration\.serializers",
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()

# Railway environment detection - check for DATABASE_URL which Railway always provides
RAILWAY_ENVIRONMENT = os.getenv('RAILWAY_ENVIRONMENT')
DATABASE_URL = os.getenv('DATABASE_URL')
IS_RAILWAY = any(key.startswith("RAILWAY_") for key in os.environ)
IS_PRODUCTION = IS_RAILWAY or bool(DATABASE_URL)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not IS_PRODUCTION and os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",") if os.getenv("ALLOWED_HOSTS") else []
if IS_PRODUCTION:
    ALLOWED_HOSTS.append('.railway.app')
    ALLOWED_HOSTS.append('mini-ecom2-production.up.railway.app')

CSRF_TRUSTED_ORIGINS = []
if IS_PRODUCTION:
    CSRF_TRUSTED_ORIGINS = [
        'https://*.railway.app',
        'https://mini-ecom2-production.up.railway.app',
    ]


FRONTEND_URL = "http://localhost:3000"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    # Third party apps
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "phonenumber_field",
    "anymail",
    # Authentication apps
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    # Social providers Needed
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.facebook",
    # 2FA
    "django_otp",
    "django_otp.plugins.otp_totp",
    "django_otp.plugins.otp_static",
    # Filters
    "django_filters",

    # Documentation
    "drf_spectacular",

    # Apps
    "accounts",
    "products",
    "cart",
    "orders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Add WhiteNoise for static files
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # 2FA
    "django_otp.middleware.OTPMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Allauth middleware
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "mini_ecom.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mini_ecom.wsgi.application"


# Database configuration
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if DATABASE_URL:
    # Railway/Production PostgreSQL configuration via DATABASE_URL
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=True,
        )
    }
else:
    # Fallback (local dev, or Railway if DATABASE_URL is not exposed)
    # IMPORTANT: Railway sets $PORT for the web process (often 8080). Do NOT use it for Postgres.
    db_name = os.getenv("PGDATABASE") or os.getenv("DB_NAME") or os.getenv("NAME")
    db_user = os.getenv("PGUSER") or os.getenv("DB_USER") or os.getenv("USER")
    db_password = os.getenv("PGPASSWORD") or os.getenv("DB_PASSWORD") or os.getenv("PASSWORD")
    db_host = os.getenv("PGHOST") or os.getenv("DB_HOST") or os.getenv("HOST")
    db_port = os.getenv("PGPORT") or os.getenv("DB_PORT") or "5432"

    has_explicit_db = all([db_name, db_user, db_password, db_host])
    if not has_explicit_db and IS_RAILWAY:
        raise ImproperlyConfigured(
            "Database not configured: set DATABASE_URL (recommended on Railway) or PG*/DB_* vars. "
            "Do not use the Railway $PORT env var for Postgres."
        )

    if has_explicit_db:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": db_name,
                "USER": db_user,
                "PASSWORD": db_password,
                "HOST": db_host,
                "PORT": db_port,
            }
        }
    else:
        # Last-resort local dev default (keeps manage.py commands usable without Postgres)
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Lagos"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise configuration for production static file serving
if IS_PRODUCTION:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

MEDIA_URL = "media/"

MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "accounts.CustomUser"


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "dj_rest_auth.jwt_auth.JWTCookieAuthentication",  # Web (cookies)
        # Mobile (header)
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_RATES": {},
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# API Documentation settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Mini Ecom API',
    'DESCRIPTION': 'E-commerce API with accounts, products, cart, orders and payments',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'TAGS': [
        {'name': 'auth', 'description': 'Authentication, Registration & Social Login'},
        {'name': 'accounts', 'description': 'User Profile, 2FA & Phone Verification'},
        {'name': 'products', 'description': 'Product Catalog & Categories'},
        {'name': 'cart', 'description': 'Shopping Cart Management'},
        {'name': 'orders', 'description': 'Orders, Checkout & Payments'},
    ]
}

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    # Needed to login users by username in django admin
    "django.contrib.auth.backends.ModelBackend",
    # allauth specific authentication method (login by email)
    "allauth.account.auth_backends.AuthenticationBackend",
]


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    # "VERIFYING_KEY": None,
    # "AUDIENCE": None,
    # "ISSUER": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    # "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
}
REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_COOKIE": "jwt-auth",
    "JWT_AUTH_REFRESH_COOKIE": "jwt-refresh",
    "JWT_AUTH_HTTPONLY": False,
    "JWT_AUTH_SAMESITE": "Lax",
    "TOKEN_MODEL": None,
    "USER_DETAILS_SERIALIZER": "accounts.serializers.CustomUserDetailsSerializer",
    "REGISTER_SERIALIZER": "accounts.serializers.CustomRegisterSerializer",
    "LOGIN_SERIALIZER": "accounts.serializers.CustomLoginSerializer",
    "EMAIL_VERIFICATION": "mandatory",
    "OLD_PASSWORD_FIELD_ENABLED": True,
    "LOGOUT_ON_PASSWORD_CHANGE": False,
    "SESSION_LOGIN": False,
    "REGISTER_PERMISSION_CLASSES": ("rest_framework.permissions.AllowAny",),
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "accounts.adapters": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# Allauth settings
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_CONFIRM_EMAIL_ON_GET = False
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"
ACCOUNT_USER_MODEL_EMAIL_FIELD = "email"
ACCOUNT_LOGOUT_ON_GET = False
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[Mini E-com]"
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http"

ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = None
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = FRONTEND_URL + "/email-verified/"
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False
ACCOUNT_EMAIL_NOTIFICATIONS = True
# Social account settings
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_QUERY_EMAIL = True

SOCIALACCOUNT_ADAPTER = "accounts.adapters.CustomSocialAccountAdapter"
ACCOUNT_ADAPTER = "accounts.adapters.CustomAccountAdapter"

ACCOUNT_MAX_EMAIL_ADDRESSES = 1
ACCOUNT_EMAIL_CONFIRMATION_HMAC = True

# Set Up STMP for sending emails
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.gmail.com"
# EMAIL_PORT = 587
# EMAIL_USE_SSL = True  # Changed from EMAIL_USE_TLS
# EMAIL_USE_TLS = False
# EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
# EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# EMAIL_TIMEOUT = 30

EMAIL_BACKEND = "anymail.backends.mailersend.EmailBackend"

ANYMAIL = {
    "MAILERSEND_API_TOKEN": os.getenv("MAILERSEND_API_TOKEN"),  
}
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")


# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# DEFAULT_FROM_EMAIL = "noreply@mini-ecom.com"

PASSWORD_RESET_TIMEOUT = 3600


OTP_TOTP_ISSUER = "Mini E-Com"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "offline",
        },
    },
    "facebook": {
        "METHOD": "oauth2",
        "SCOPE": ["email", "public_profile"],
        "AUTH_PARAMS": {"auth_type": "rerequest"},
        "INIT_PARAMS": {"cookie": True},
        "FIELDS": [
            "id",
            "email",
            "first_name",
            "last_name",
            "middle_name",
            "name",
            "name_format",
            "picture",
            "short_name",
        ],
        "EXCHANGE_TOKEN": True,
        "VERIFIED_EMAIL": False,
        "VERSION": "v24.0",
    },
}
SOCIALACCOUNT_GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
SOCIALACCOUNT_GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
SOCIALACCOUNT_FACEBOOK_CLIENT_ID = os.getenv("FACEBOOK_CLIENT_ID")
SOCIALACCOUNT_FACEBOOK_CLIENT_SECRET = os.getenv("FACEBOOK_CLIENT_SECRET")

TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
TWILIO_PHONE_NUMBER = os.getenv("TWILIO_PHONE_NUMBER")

STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")

# Redis configuration for caching and sessions
if IS_PRODUCTION:
    # Railway Redis configuration via REDIS_URL
    REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379')
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": f"{REDIS_URL}/0",
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "CONNECTION_POOL_KWARGS": {"max_connections": 50, "retry_on_timeout": True},
                "SOCKET_CONNECT_TIMEOUT": 5,
                "SOCKET_TIMEOUT": 5,
                "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
                "IGNORE_EXCEPTIONS": True,
            },
            "KEY_PREFIX": "mini_ecom",
            "TIMEOUT": 300,
        },
        "sessions": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": f"{REDIS_URL}/1",
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
            "KEY_PREFIX": "session",
        },
    }
else:
    # Local Redis configuration
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": "redis://127.0.0.1:6379/1",
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "CONNECTION_POOL_KWARGS": {"max_connections": 50, "retry_on_timeout": True},
                "SOCKET_CONNECT_TIMEOUT": 5,
                "SOCKET_TIMEOUT": 5,
                "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
                "IGNORE_EXCEPTIONS": True,
            },
            "KEY_PREFIX": "mini_ecom",
            "TIMEOUT": 300,
        },
        "sessions": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": "redis://127.0.0.1:6379/2",
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
            "KEY_PREFIX": "session",
        },
    }


SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
SESSION_CACHE_ALIAS = "sessions"
SESSION_COOKIE_AGE = 1209600
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = "Lax"

PHONE_VERIFICATION = {
    "CODE_LENGTH": 6,
    "CODE_EXPIRY_MINUTES": 10,
    "MAX_ATTEMPTS": 5,
    "RATE_LIMIT_CODES_PER_HOUR": 3,
    "RATE_LIMIT_VERIFICATIONS_PER_MINUTE": 5,
    "USE_REDIS": True,
    "REDIS_KEY_PREFIX": "phone_verify",
}
