# Generated by Django 5.2.8 on 2025-11-26 22:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimage",
            old_name="is_feature",
            new_name="is_featured",
        ),
    ]
